spring:
  application:
    name: ESG-Backend
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    # store-type: redis
    # 30 ???
    timeout: 2592000

  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ESG
    username: root
    password: Pty-990827
#    password: ZbW55866

  mail:
    host: smtp.163.com
    username: pantianyu0827@163.com
    password: OETBZTXNTWTZYNCR
    port: 587
    protocol: smtp
    properties:
      "mail.smtp.ssl.enable": true
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true


server:
  port: 8080
  servlet:
    context-path:
